# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class cia < Formula
    desc "CIA is your go-to CLI tool for analyzing container images. It can pull images, scan for vulnerabilities, and output reports in multiple formats"
    homepage "https://github.com/moabukar/cia"
    version "0.0.1"
  
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/moabukar/cia/releases/download/v0.2.2/cia_v0.2.2_darwin_amd64.tar.gz"
        sha256 "95d170e99eb65e1475aeb088d2f6f58d3d8acea50098132c6318d83fb2253ef5"
  
        def install
          bin.install "cia"
        end
      end
      if Hardware::CPU.arm?
        url "https://github.com/moabukar/cia/releases/download/v0.2.2/cia_v0.2.2_darwin_arm64.tar.gz"
        sha256 "1ad48ef30c57e8df0eef7abe472034520f0026a88a963e6cff179983431f4983"
  
        def install
          bin.install "cia"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/moabukar/cia/releases/download/v0.2.2/cia_v0.2.2_linux_arm64.tar.gz"
        sha256 "b0e5c482122310aaeb56960d58c32711e824325f9481aac7d73fec5f4a614ec6"
  
        def install
          bin.install "cia"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/moabukar/cia/releases/download/v0.2.2/cia_v0.2.2_linux_amd64.tar.gz"
        sha256 "802b960d77db656a9050d78646816cc2eeb654369186da367c5428ecc00167a0"
  
        def install
          bin.install "cia"
        end
      end
    end
  end