# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class techvault < Formula
    desc "techvault is the CLI tool for generating random questions from Tech Vault"
    homepage "https://github.com/moabukar/techvault"
    version "0.1.0"
  
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/moabukar/tech-vault-cli/releases/download/v0.1.0/tech-vault-cli_0.1.0_darwin_amd64.tar.gz"
        sha256 "95d170e99eb65e1475aeb088d2f6f58d3d8acea50098132c6318d83fb2253ef5"
  
        def install
          bin.install "techvault"
        end
      end
      if Hardware::CPU.arm?
        url "https://github.com/moabukar/tech-vault-cli/releases/download/v0.1.0/tech-vault-cli_0.1.0_darwin_amd64.tar.gz"
        sha256 "1ad48ef30c57e8df0eef7abe472034520f0026a88a963e6cff179983431f4983"
  
        def install
          bin.install "techvault"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/moabukar/tech-vault-cli/releases/download/v0.1.0/tech-vault-cli_0.1.0_linux_amd64.tar.gz"
        sha256 "b0e5c482122310aaeb56960d58c32711e824325f9481aac7d73fec5f4a614ec6"
  
        def install
          bin.install "techvault"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/moabukar/techvault/releases/download/v0.2.2/techvault_v0.2.2_linux_amd64.tar.gz"
        sha256 "802b960d77db656a9050d78646816cc2eeb654369186da367c5428ecc00167a0"
  
        def install
          bin.install "techvault"
        end
      end
    end
  end
